businessLogic.FacadeImplementationWS
NAME
businessLogic.FacadeImplementationWS
SYNOPSIS
Inherits businessLogic.ApplicationFacadeInterfaceWS.
Public Member Functions
FacadeImplementationWS ()
Offer createOffer (RuralHouse ruralHouse, Date firstDay, Date lastDay, float price) throws OverlappingOfferExists, BadDates
This method creates an offer with a house number, first day, last day and price.
Vector< RuralHouse > getAllRuralHouses ()
This method creates a book with a corresponding parameters.
Vector< Offer > getOffers (RuralHouse rh, Date firstDay, Date lastDay)
This method obtains the offers of a ruralHouse in the provided dates.
void initializeBD ()
void bookOffer (Offer bookOffer)
boolean coincide (RuralHouse houseCode, Date firstDay, Date lastDay)
Detailed Description
Definition at line 22 of file FacadeImplementationWS.java.
Constructor & Destructor Documentation
businessLogic.FacadeImplementationWS.FacadeImplementationWS ()
Definition at line 28 of file FacadeImplementationWS.java.
                                    {
    }
Member Function Documentation
void businessLogic.FacadeImplementationWS.bookOffer (Offer bookOffer)
Implements businessLogic.ApplicationFacadeInterfaceWS.
Definition at line 111 of file FacadeImplementationWS.java.
                                           {
        HibernateDataAccess HDA = new HibernateDataAccess();
        HDA.bookOffer(bookOffer);
    }
References dataAccess.HibernateDataAccess.bookOffer().
boolean businessLogic.FacadeImplementationWS.coincide (RuralHouse houseCode, Date firstDay, Date lastDay)
Implements businessLogic.ApplicationFacadeInterfaceWS.
Definition at line 117 of file FacadeImplementationWS.java.
                                                                               {
        HibernateDataAccess HDA = new HibernateDataAccess();
        boolean a = HDA.coincide(houseCode, firstDay, lastDay);
        return a;
    }
References dataAccess.HibernateDataAccess.coincide().
Offer businessLogic.FacadeImplementationWS.createOffer (RuralHouse ruralHouse, Date firstDay, Date lastDay, float price) throws OverlappingOfferExists, BadDates
This method creates an offer with a house number, first day, last day and price.
Parameters:
House number, start day, last day and price
Returns:
the created offer, or null, or an exception
Implements businessLogic.ApplicationFacadeInterfaceWS.
Definition at line 40 of file FacadeImplementationWS.java.
                                                    {
        HibernateDataAccess dbManager = new HibernateDataAccess();
        Offer o = null;
        if (firstDay.compareTo(lastDay) >= 0) {
            throw new BadDates();
        }
        boolean b = dbManager.existsOverlappingOffer(ruralHouse, firstDay, lastDay);
        if (!b)
            o = dbManager.createOffer(ruralHouse, firstDay, lastDay, price);
        return o;
    }
References dataAccess.HibernateDataAccess.createOffer(), and dataAccess.HibernateDataAccess.existsOverlappingOffer().
Vector<RuralHouse> businessLogic.FacadeImplementationWS.getAllRuralHouses ()
This method creates a book with a corresponding parameters.
Parameters:
First day, last day, house number and telephone
Returns:
a bookThis method retrieves the existing rural houses
a Set of rural houses
Implements businessLogic.ApplicationFacadeInterfaceWS.
Definition at line 56 of file FacadeImplementationWS.java.
                                                  {
        HibernateDataAccess dbManager = new HibernateDataAccess();
        Vector<RuralHouse> ruralHouses = dbManager.getAllRuralHouses();
        return ruralHouses;
    }
References dataAccess.HibernateDataAccess.getAllRuralHouses().
Vector<Offer> businessLogic.FacadeImplementationWS.getOffers (RuralHouse rh, Date firstDay, Date lastDay)
This method obtains the offers of a ruralHouse in the provided dates.
Parameters:
ruralHouse,the ruralHouse to inspect
firstDay,first day in a period range
lastDay,last day in a period range
Returns:
the first offer that overlaps with those dates, or null if there is no overlapping offer
Implements businessLogic.ApplicationFacadeInterfaceWS.
Definition at line 76 of file FacadeImplementationWS.java.
                                                                               {
        HibernateDataAccess dbManager = new HibernateDataAccess();
        Vector<Offer> offers = new Vector<Offer>();
        offers = dbManager.getOffers(rh, firstDay, lastDay);
        return offers;
    }
References dataAccess.HibernateDataAccess.getOffers().
void businessLogic.FacadeImplementationWS.initializeBD ()
Implements businessLogic.ApplicationFacadeInterfaceWS.
Definition at line 83 of file FacadeImplementationWS.java.
                               {
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        try {
            @SuppressWarnings("unchecked")
            List<RuralHouse> query = session.createQuery("FROM RuralHouse").list();
            Iterator<RuralHouse> i = query.iterator();
            while (i.hasNext()) {
                RuralHouse rh = i.next();
                session.delete(rh);
            }
            RuralHouse rh1 = new RuralHouse("Ezkioko etxea", "Ezkio");
            RuralHouse rh2 = new RuralHouse("Etxetxikia", "Iruna");
            RuralHouse rh3 = new RuralHouse("Udaletxea", "Bilbo");
            RuralHouse rh4 = new RuralHouse("Gaztetxea", "Renteria");
            session.save(rh1);
            session.save(rh2);
            session.save(rh3);
            session.save(rh4);
            session.getTransaction().commit();
            System.out.println("Db initialized");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
References modelo.dominio.HibernateUtil.getSessionFactory().
Author
Generated automatically by Doxygen for Rural_House from the source code.