dataAccess.HibernateDataAccess
NAME
dataAccess.HibernateDataAccess
SYNOPSIS
Public Member Functions
Offer createOffer (RuralHouse ruralHouse, Date firstDay, Date lastDay, float price)
Vector< RuralHouse > getAllRuralHouses ()
Vector< Offer > getOffers (RuralHouse rh, Date firstDay, Date lastDay)
boolean existsOverlappingOffer (RuralHouse rh, Date firstDay, Date lastDay) throws OverlappingOfferExists
void bookOffer (Offer o)
boolean coincide (RuralHouse houseCode, Date firstDay, Date lastDay)
Detailed Description
Definition at line 16 of file HibernateDataAccess.java.
Member Function Documentation
void dataAccess.HibernateDataAccess.bookOffer (Offer o)
Definition at line 77 of file HibernateDataAccess.java.
                                   {
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        int offerNumber = o.getOfferNumber();
        session.createQuery("update Offer set book = 'YES' where offerNumber = '" + offerNumber + "'").executeUpdate();
        session.getTransaction().commit();
    }
References domain.Offer.getOfferNumber(), and modelo.dominio.HibernateUtil.getSessionFactory().
Referenced by businessLogic.FacadeImplementationWS.bookOffer().
boolean dataAccess.HibernateDataAccess.coincide (RuralHouse houseCode, Date firstDay, Date lastDay)
Definition at line 85 of file HibernateDataAccess.java.
                                                                               {
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        List<Offer> query = session.createQuery("from Offer where houseNumber='" + houseCode + "'").list();
        int cont = 0;
        for (int i = 0; i < query.size(); i++) {
            if (((firstDay.compareTo(query.get(i).getFirstDay()) >= 0)
                    && (lastDay.compareTo(query.get(i).getLastDay()) <= 0))
                    || ((firstDay.compareTo(query.get(i).getFirstDay()) <= 0)
                            && (lastDay.compareTo(query.get(i).getLastDay()) >= 0))
                    || ((firstDay.compareTo(query.get(i).getFirstDay()) >= 0)
                            && (firstDay.compareTo(query.get(i).getLastDay()) <= 0))) {
                cont++;
            }
        }
        if (cont > 0) {
            session.getTransaction().commit();
            return true;
        } else {
            session.getTransaction().commit();
            return false;
        }
    }
References modelo.dominio.HibernateUtil.getSessionFactory().
Referenced by businessLogic.FacadeImplementationWS.coincide().
Offer dataAccess.HibernateDataAccess.createOffer (RuralHouse ruralHouse, Date firstDay, Date lastDay, float price)
Definition at line 18 of file HibernateDataAccess.java.
                                                                                              {
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        try {
            Integer houseCode = ruralHouse.getHouseNumber();
            List<RuralHouse> query = session.createQuery("from RuralHouse where houseNumber='" + houseCode + "'")
                    .list();
            RuralHouse rh = query.get(0);
            Offer o = rh.createOffer(firstDay, lastDay, price);
            session.save(o);
            session.getTransaction().commit();
            return o;
        } catch (Exception e) {
            return null;
        }
    }
References domain.RuralHouse.createOffer(), domain.RuralHouse.getHouseNumber(), and modelo.dominio.HibernateUtil.getSessionFactory().
Referenced by businessLogic.FacadeImplementationWS.createOffer().
boolean dataAccess.HibernateDataAccess.existsOverlappingOffer (RuralHouse rh, Date firstDay, Date lastDay) throws OverlappingOfferExists
Definition at line 61 of file HibernateDataAccess.java.
                                                                                                                    {
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        try {
            Integer houseCode = rh.getHouseNumber();
            List<RuralHouse> query = session.createQuery("from RuralHouse where houseNumber='" + houseCode + "'")
                    .list();
            RuralHouse rhn = query.get(0);
            if (rhn.overlapsWith(firstDay, lastDay) != null)
                return true;
        } catch (Exception e) {
            return true;
        }
        return false;
    }
References modelo.dominio.HibernateUtil.getSessionFactory(), and domain.RuralHouse.overlapsWith().
Referenced by businessLogic.FacadeImplementationWS.createOffer().
Vector<RuralHouse> dataAccess.HibernateDataAccess.getAllRuralHouses ()
Definition at line 36 of file HibernateDataAccess.java.
                                                  {
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        Vector<RuralHouse> allRuralHouses = new Vector<RuralHouse>();
        @SuppressWarnings("unchecked")
        List<RuralHouse> query = session.createQuery("from RuralHouse").list();
        session.getTransaction().commit();
        Iterator<RuralHouse> i = query.iterator();
        while (i.hasNext()) {
            allRuralHouses.add(i.next());
        }
        return allRuralHouses;
    }
References modelo.dominio.HibernateUtil.getSessionFactory().
Referenced by businessLogic.FacadeImplementationWS.getAllRuralHouses().
Vector<Offer> dataAccess.HibernateDataAccess.getOffers (RuralHouse rh, Date firstDay, Date lastDay)
Definition at line 50 of file HibernateDataAccess.java.
                                                                               {
        Integer houseCode = rh.getHouseNumber();
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        Vector<Offer> allOffers = new Vector<Offer>();
        List<RuralHouse> query = session.createQuery("from RuralHouse where houseNumber='" + houseCode + "'").list();
        RuralHouse rh1 = (RuralHouse) query.get(0);
        allOffers = rh1.getOffers(firstDay, lastDay);
        return allOffers;
    }
References domain.RuralHouse.getHouseNumber(), domain.RuralHouse.getOffers(), and modelo.dominio.HibernateUtil.getSessionFactory().
Referenced by businessLogic.FacadeImplementationWS.getOffers().
Author
Generated automatically by Doxygen for Rural_House from the source code.