domain.RuralHouse
NAME
domain.RuralHouse
SYNOPSIS
Public Member Functions
Set< Offer > getOffers ()
void setOffers (Set< Offer > offers)
RuralHouse ()
RuralHouse (String description, String city)
Integer getHouseNumber ()
void setHouseNumber (Integer houseNumber)
String getDescription ()
void setDescription (String description)
String getCity ()
void setCity (String city)
Offer createOffer (Date firstDay, Date lastDay, float price)
This method creates an offer with a house number, first day, last day and price.
int hashCode ()
String toString ()
boolean equals (Object obj)
Vector< Offer > getOffers (Date firstDay, Date lastDay)
This method obtains available offers for a concrete house in a certain period.
Offer overlapsWith (Date firstDay, Date lastDay)
This method obtains the first offer that overlaps with the provided dates.
Public Attributes
Set< Offer > offers
Private Attributes
Integer houseNumber
String description
String city
Detailed Description
Definition at line 10 of file RuralHouse.java.
Constructor & Destructor Documentation
domain.RuralHouse.RuralHouse ()
Definition at line 27 of file RuralHouse.java.
                        {
    }
Referenced by domain.RuralHouse.equals().
domain.RuralHouse.RuralHouse (String description, String city)
Definition at line 31 of file RuralHouse.java.
                                                       {
        this.description = description;
        this.city = city;
        offers=new HashSet<Offer>();
    }
References domain.RuralHouse.city, domain.RuralHouse.description, and domain.RuralHouse.offers.
Member Function Documentation
Offer domain.RuralHouse.createOffer (Date firstDay, Date lastDay, float price)
This method creates an offer with a house number, first day, last day and price.
Parameters:
House number, start day, last day and price
Returns:
None
Definition at line 71 of file RuralHouse.java.
                                                                        {
        //System.out.println("LLAMADA RuralHouse createOffer, offerNumber="+" firstDay="+firstDay+" lastDay="+lastDay+" price="+price);
        Offer off=new Offer(firstDay,lastDay,price,this);
        offers.add(off);
        return off;
    }
References domain.RuralHouse.offers.
Referenced by dataAccess.HibernateDataAccess.createOffer().
boolean domain.RuralHouse.equals (Object obj)
Definition at line 94 of file RuralHouse.java.
                                      {
        RuralHouse other = (RuralHouse) obj;
        if (this == obj)
          return true;
        if (obj == null)
          return false;
        if (getClass() != obj.getClass())
          return false;
// if (houseNumber != other.houseNumber) // NO COMPARAR ASÍ ya que houseNumber NO ES "int" sino objeto de "java.lang.Integer"
        if (!houseNumber.equals(other.houseNumber))
          return false;
        return true;
    }
References domain.RuralHouse.houseNumber, and domain.RuralHouse.RuralHouse().
String domain.RuralHouse.getCity ()
Definition at line 54 of file RuralHouse.java.
                            {
        return city;
    }
References domain.RuralHouse.city.
String domain.RuralHouse.getDescription ()
Definition at line 45 of file RuralHouse.java.
                                   {
        return description;
    }
References domain.RuralHouse.description.
Integer domain.RuralHouse.getHouseNumber ()
Definition at line 37 of file RuralHouse.java.
                                    {
        return houseNumber;
    }
References domain.RuralHouse.houseNumber.
Referenced by dataAccess.HibernateDataAccess.createOffer(), and dataAccess.HibernateDataAccess.getOffers().
Set<Offer> domain.RuralHouse.getOffers ()
Definition at line 19 of file RuralHouse.java.
                                  {
        return offers;
    }
References domain.RuralHouse.offers.
Referenced by dataAccess.HibernateDataAccess.getOffers().
Vector<Offer> domain.RuralHouse.getOffers (Date firstDay, Date lastDay)
This method obtains available offers for a concrete house in a certain period.
Parameters:
houseNumber,the house number where the offers must be obtained
firstDay,first day in a period range
lastDay,last day in a period range
Returns:
a HashSet of offers(Offer class) available in this period
Definition at line 116 of file RuralHouse.java.
                                                                  {
        
        Vector<Offer> availableOffers=new Vector<Offer>();
        Iterator<Offer> e=offers.iterator();
        Offer offer;
        while (e.hasNext()){
            offer=e.next();
            if ( ((offer.getFirstDay().compareTo(firstDay) >= 0) && (offer.getLastDay().compareTo(lastDay) <= 0)) && (offer.getBook().equals("NO"))) {
                    availableOffers.add(offer);
            }
        }
        return availableOffers;
        
    }
References domain.Offer.getBook(), domain.Offer.getFirstDay(), domain.Offer.getLastDay(), and domain.RuralHouse.offers.
int domain.RuralHouse.hashCode ()
Definition at line 80 of file RuralHouse.java.
                          {
        final int prime = 31;
        int result = 1;
        result = prime * result + houseNumber.hashCode();
        return result;
    }
References domain.RuralHouse.houseNumber.
Offer domain.RuralHouse.overlapsWith (Date firstDay, Date lastDay)
This method obtains the first offer that overlaps with the provided dates.
Parameters:
firstDay,first day in a period range
lastDay,last day in a period range
Returns:
the first offer that overlaps with those dates, or null if there is no overlapping offer
Definition at line 141 of file RuralHouse.java.
                                                             {
        
        Iterator<Offer> e=offers.iterator();
        Offer offer=null;
        while (e.hasNext()){
            offer=e.next();
            if ( (offer.getFirstDay().compareTo(lastDay)<0) && (offer.getLastDay().compareTo(firstDay)>0))
                return offer;
        }
        return null;
        
    }
References domain.Offer.getFirstDay(), domain.Offer.getLastDay(), and domain.RuralHouse.offers.
Referenced by dataAccess.HibernateDataAccess.existsOverlappingOffer().
void domain.RuralHouse.setCity (String city)
Definition at line 58 of file RuralHouse.java.
                                     {
        this.city=city;
    }
References domain.RuralHouse.city.
void domain.RuralHouse.setDescription (String description)
Definition at line 49 of file RuralHouse.java.
                                                   {
        this.description=description;
    }
References domain.RuralHouse.description.
void domain.RuralHouse.setHouseNumber (Integer houseNumber)
Definition at line 41 of file RuralHouse.java.
                                                    {
        this.houseNumber = houseNumber;
    }
References domain.RuralHouse.houseNumber.
void domain.RuralHouse.setOffers (Set< Offer > offers)
Definition at line 23 of file RuralHouse.java.
                                             {
        this.offers = offers;
    }
References domain.RuralHouse.offers.
String domain.RuralHouse.toString ()
Definition at line 89 of file RuralHouse.java.
                             {
        return this.houseNumber + ": " + this.city;
    }
References domain.RuralHouse.city.
Member Data Documentation
String domain.RuralHouse.city [private]
Definition at line 15 of file RuralHouse.java.
Referenced by domain.RuralHouse.getCity(), domain.RuralHouse.RuralHouse(), domain.RuralHouse.setCity(), and domain.RuralHouse.toString().
String domain.RuralHouse.description [private]
Definition at line 14 of file RuralHouse.java.
Referenced by domain.RuralHouse.getDescription(), domain.RuralHouse.RuralHouse(), and domain.RuralHouse.setDescription().
Integer domain.RuralHouse.houseNumber [private]
Definition at line 13 of file RuralHouse.java.
Referenced by domain.RuralHouse.equals(), domain.RuralHouse.getHouseNumber(), domain.RuralHouse.hashCode(), and domain.RuralHouse.setHouseNumber().
Set<Offer> domain.RuralHouse.offers
Definition at line 16 of file RuralHouse.java.
Referenced by domain.RuralHouse.createOffer(), domain.RuralHouse.getOffers(), domain.RuralHouse.overlapsWith(), domain.RuralHouse.RuralHouse(), and domain.RuralHouse.setOffers().
Author
Generated automatically by Doxygen for Rural_House from the source code.